### ISSUE TITLE
On hover show the color profile picture of users

### ISSUE THREAD

**Issue by kymppi** [novuhq/website#15]
## What?
The contributors page currently is pretty much black and white. It would be cool to have some color or something

## Why?
not really important but something for UX

## How?
Possibly show the right color of the user profile pic when hovering? Also these: 
![image](https://user-images.githubusercontent.com/48528700/175974053-6d2791bf-bef2-4d22-8bc2-7fb7d0671f61.png)
could have some hover effect for example getting color i have some ideas.

**Comment by andrewgolovanov** [comment]
@kymppi @scopsy Hi guys! 
I've added some updates for the profile images, now when hovered over the original colors are shown :sparkles:

[Example](https://websitemain13551-contributoravatars.gtsb.io/contributors/)

**Comment by kymppi** [comment]
Wow, looks awesome, just what i suggested. I think it brings a lot more color to the page?
