### ISSUE TITLE
change the scrollbar or make same

### ISSUE THREAD

**Issue by PritamSarbajna** [novuhq/website#21]
## What?
change the scrollbar  of novu.co and docs.novu.co or make same.

## How?
I can change the scrollbar entirely with a custom scrollbar or I can make both scrollbar look same.

## Other information :
![Screenshot (169)](https://user-images.githubusercontent.com/90236635/182027552-8d2b059c-1c5d-4f7e-8903-88772496a25f.png)

![Screenshot (168)](https://user-images.githubusercontent.com/90236635/182027570-4d25fd78-2f14-4db6-823b-5120043c7007.png)

**Comment by scopsy** [comment]
Hi @andrewgolovanov , @PritamSarbajna is trying to update the styling of the scroll bar but doesn't sure where it is best to make the changes in terms of CSS files. He will be provide details here in a bit if you could help guide him with this one 🙏

**Comment by PritamSarbajna** [comment]
Hi I'm trying to solve this issue but in locally when I'm trying to create a custom css file for scrollbar, It isn't showing any changes and also note that I'm trying to do this without gatsby 

![Screenshot (177)](https://user-images.githubusercontent.com/90236635/182133000-6feef686-b206-4179-abd3-def292517b1e.png)

**Comment by andrewgolovanov** [comment]
Hello @PritamSarbajna!
Sorry for the late reply, I got lost in the notifications :sweat_smile:

You can add the required styles to an existing file called `global.css`

Please let me know if you've any questions when testing :pray:

**Comment by andrewgolovanov** [comment]
@PritamSarbajna I think we can use the `color-scheme` property with the value `dark` which is a simple solution that will help us apply the styles we want to the scrollbar on the site

more about this property you can read [here](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme)

It seems to work great for me :sparkles:
I'll be glad to hear your opinion about it

Example:
<img width="826" alt="Screenshot 2022-08-03 at 00 35 18" src="https://user-images.githubusercontent.com/17677196/182479510-311f397d-947a-4df5-bc7d-96fe404c98d3.png">
<img width="1964" alt="Screenshot 2022-08-03 at 00 48 38" src="https://user-images.githubusercontent.com/17677196/182479513-2424b061-d838-4fb3-8245-0c73adb73412.png">

**Comment by PritamSarbajna** [comment]
Hi @andrewgolovanov oh yeah of course it should work why I didn't think of it 😅

**Comment by andrewgolovanov** [comment]
@PritamSarbajna Thank you! :raised_hands:
