### ISSUE TITLE
Problem with the Podcast page

### ISSUE THREAD

**Issue by nevo-david** [novuhq/website#37]
There is a slight problem with the podcast page. As you can see, it says:
"Enterprise Selling Amplication"
but according to the XML
view-source:https://feeds.transistor.fm/sourcelife

it's supposed to be "Enterprise Selling w/ Amplication"

**Comment by Rutam21** [comment]
@nevo-david I can fix this.

**Comment by slayeh17** [comment]
> @nevo-david I can fix this.

Hey, are you doing this? if yes, did you find the file where "Enterprise Selling Amplication" is located?
