### ISSUE TITLE
🚀 Feature:  create floating button to take to top of the page.

### ISSUE THREAD

**Issue by saimaheshtaduri** [novuhq/website#54]
### 🔖 Feature description

The feature is to a floating action button, on click takes to the top of the page.

### 🎤 Why is this feature needed ?

As pages are getting longer, it is important to have a FAB that could take you quickly to the nav bar ( top of the page )

### ✌️ How do you aim to achieve this?

I can add a FAB component and add it to each page, so that the user can easily navigate to the top of the page.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
@andrewgolovanov, what do you think about this? Could we create a design for that so perhaps @saimaheshtaduri can help with implementation?

**Comment by saimaheshtaduri** [comment]
Yes. I would be glad to contribute ! @scopsy

**Comment by andrewgolovanov** [comment]
@scopsy I'll talk to the designers and get their opinions on the matter next Monday
As soon as I get feedback I'll let you know about it :rocket:

**Comment by oba2311** [comment]
@andrewgolovanov  thanks!

**Comment by oneknucklehead** [comment]
Hey! is this issue still up for grab?

**Comment by gambhirsharma** [comment]
Is anybody working on this issue?

**Comment by karthiknadar1204** [comment]
If this issue is still.open please assign it to me
