### ISSUE TITLE
🚀 Feature: Create sitemap.xml and add sitelinks for SEO

### ISSUE THREAD

**Issue by ShaneMaglangit** [novuhq/website#58]
### 🔖 Feature description

Currently, Google search results for Novu is very minimal with only a single sentence description. Adding a sitemap with sitelinks can be useful for someone looking for a quick link to other parts of the site (Hacktoberfest, Blogs, Documentation, etc..).

![image](https://user-images.githubusercontent.com/53674742/195328258-2f24b86f-33ed-4ecf-95fc-2c2b9e39e897.png)

Take Nextjs' search result for example:

![image](https://user-images.githubusercontent.com/53674742/195328765-701dbe12-1018-4239-aae2-713de263f606.png)

### 🎤 Why is this feature needed ?

Improve SEO and reduce navigation steps needed to go to important sub pages such as Quick Start, Documentation, Blogs, etc.

### ✌️ How do you aim to achieve this?

- ~~Add sitemap.xml under `app/web` and specify sitelinks for important and frequently visited pages.~~
- Add sitelinks based on https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/
- Submit sitemap to https://search.google.com/search-console/sitemaps

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
@ShaneMaglangit transfered the issue to the correct repository :) The changes you are proposing are perfect! And it will be really helpful to add them.

Do you want to help with this?

**Comment by ShaneMaglangit** [comment]
Oh, I was unaware that is a separate repository for the marketing site.

I am quite occupied atm. Let's keep it open for other contributors for now 😁

**Comment by ShaneMaglangit** [comment]
@nevo-david I see, perhaps a better way to phrase this feature request is: to add additional sitelinks on the current sitemap.xml.

I've looked at the link you just sent and as you may notice, it actually has no proper content. It doesn't specify routes/paths of the website.

**Comment by ShaneMaglangit** [comment]
May you reconsider if this is an issue that should be closed?

I just think that this would be a great change to help with SEO and have software look more mature in search results.

The existing sitemap you linked actually does nothing with its current content.

I feel like it is not something we should ignore since it practically requires zero effort to update and maintain but greatly benefits the project.

**Comment by ShaneMaglangit** [comment]
Oh I see now, I didn't look at sitemap-0.xml.
