### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jyotika6221** [novuhq/website#61]

**Comment by jyotika6221** [comment]
Pls assign me this issue.

**Comment by Vanshiii203** [comment]
@nevo-david plz assign me this issue

**Comment by scopsy** [comment]
@jyotika6221 sorry, missed this issue in the repo :( Could you use the existing contributing.md contents from novuhq/novu and add it here?

**Comment by akebu6** [comment]
@scopsy is this still open because I can see there is still no contributing.md nor did the person reply. If it's still open I would like to work on it

**Comment by scopsy** [comment]
@akebu6 sure thing! Let me assign you on that.

**Comment by akebu6** [comment]
@scopsy I have created a PR for the issue.
