### ISSUE TITLE
Navigation Links are broken on mobile

### ISSUE THREAD

**Issue by BiswaViraj** [novuhq/website#8]
The navigation link Text is missing on the mobile view,

<img width="235" alt="image" src="https://user-images.githubusercontent.com/29251776/172908279-85fc1545-d057-4aef-839e-02ec0fcd36a5.png">

<img width="321" alt="image" src="https://user-images.githubusercontent.com/29251776/172908988-fbd52b38-0c0c-48b0-a63d-a54aca3bc1d4.png">

**Comment by andrewgolovanov** [comment]
Hi @BiswaViraj!
Oh, really
Thank you for the great catch :raised_hands:
That's very helpful!

**Comment by BiswaViraj** [comment]
Thanks, @andrewgolovanov , Happy to help 😃
