### ISSUE TITLE
🐛 Bug Report: UX bug on pricing page tooltip

### ISSUE THREAD

**Issue by jonathimer** [novuhq/website#92]
if you scroll down on https://novu.co/pricing/ and hover over tooltip, the tooltip window gets overlayed by the bar

probably the tooltip has a different z-index when the tooltip gets displayed on the bottom of the bar

<img width="1728" alt="Bildschirmfoto 2023-06-12 um 16 21 30" src="https://github.com/novuhq/website/assets/41432658/e9b638c2-6627-4dfc-b30b-21a0ac23875a">

**Comment by Love-Becca** [comment]
I will like to work on this
